### PR TITLE
Gtkdoc hdr patches

### PR DESCRIPTION
**Pull request by codebrainz**
Various superficial/cosmetic cleanups to the new Python script.

### CODE REVIEW

**Comment by codebrainz** [comment]
For the last patch to improve Autoconf check, maybe it should fail gracefully if Python _or_ lxml aren't installed, instead of the hard-fail the patch adds?

**Comment by kugel-** [comment]
Well I implemented it optionally, just like doxygen (which this kind of depends on) so it would make sense.

**Comment by codebrainz** [comment]
Added commit to make it depend on Python and LXML package.

**Comment by b4n** [comment]
Mostly LGTM

**Comment by kugel-** [comment]
All the commits have been cherry-picked and are in geany master by now.

**Pull request closed without merging**
